name: ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  hidden_drawer_menu: ^1.1.2
  flare_flutter:
  smooth_star_rating: ^1.0.3
  analog_clock: ^0.0.2
  day_night_switch:
  flutter_sticky_header: ^0.4.2
  draggable_scrollbar: ^0.0.4
  imageview360: ^1.0.0
  flutter_datetime_picker:


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lib/images/jordon.png
   - lib/images/jordon1.png
   - lib/images/jordon2.png
   - lib/images/yy.png
   - lib/images/spotify.jpg
   - lib/images/1.jpg
   - lib/images/2.jpg
   - lib/images/3.jpg
   - lib/images/4.jpg
   - lib/images/5.jpg
   - lib/images/6.jpg
   - lib/images/7.jpg
   - lib/images/8.jpg
   - lib/images/9.jpg
   - lib/images/10.jpg
   - lib/images/11.jpg
   - lib/images/12.jpg
   - lib/images/13.jpg
   - lib/images/14.jpg
   - lib/images/15.jpg
   - lib/images/16.jpg
   - lib/images/17.jpg
   - lib/images/18.jpg
   - lib/images/19.jpg
   - lib/images/20.jpg
   - lib/images/21.jpg
   - lib/images/22.jpg
   - lib/images/23.jpg
   - lib/images/24.jpg
   - lib/images/25.jpg
   - lib/images/26.jpg
   - lib/images/27.jpg
   - lib/images/28.jpg
   - lib/images/29.jpg
   - lib/images/30.jpg
   - lib/images/31.jpg
   - lib/images/32.jpg
   - lib/images/34.jpg
   - lib/images/33.jpg
   - lib/images/36.jpg
   - lib/images/35.jpg
   - lib/images/curve.flr
  
 


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
